export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const FETCH_PLANETS = "FETCH_PLANETS";
export const INCREASE_VEHICLE_COUNT = "INCREASE_VEHICLE_COUNT";
export const DECREASE_VEHICLE_COUNT = "DECREASE_VEHICLE_COUNT";
export const UPDATE_TOTALSEARCH_TIME = "UPDATE_TOTALSEARCH_TIME";
export const GET_API_TOKEN = "GET_API_TOKEN";
export const HANDLE_ERRORS = "HANDLE_ERRORS";
export const FIND_FALCONE = "FIND_FALCONE";